const INIT_TASK = 'INIT_TASK';
const ADD_TASK = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const START_SAVE_TASKS = 'START_SAVE_TASKS';
const SAVE_TASKS = 'SAVE_TASKS';
const SAVE_TASKS_SUCCESS = 'SAVE_TASKS_SUCCESS';
const SAVE_TASKS_FAIL = 'SAVE_TASKS_FAIL';


export default {
    INIT_TASK,
    ADD_TASK,
    UPDATE_TASK,
    START_SAVE_TASKS,
    SAVE_TASKS,
    SAVE_TASKS_SUCCESS,
    SAVE_TASKS_FAIL
}

